### ISSUE TITLE
[von Andreas] Automatische Generierung der Barcodes

### ISSUE THREAD

**Issue by yannick9906** [yannick9906/sas-entrance#13]

**Comment by yannick9906** [comment]
Aufbau der Barcodes wieder wie letztes mal?
2 0160XXXYYYYY
x = Datum des Erstelltages y= zufällige Zahl

**Comment by yannick9906** [comment]
jup

**Comment by yannick9906** [comment]
XXXXXXXXYYVZZ <- Klasse 05-10
XXXXXXXXYYZZZ <- Oberstufe
XXXXXXXX2ZZZZ <- Visa
X = Datum Y = Klassenstufe V = a,b,c,d,e,f (genaue Klassenbezeichnung) Z = zufällige Zahl

**Comment by JanikNex** [comment]
Excel-Tabelle und Zufallsgenerator ftw!
