### ISSUE TITLE
Export als Druckfertige Ausweise

### ISSUE THREAD

**Issue by yannick9906** [yannick9906/sas-entrance#14]
Leere Seite mit den Ausweisen (2? Pro Zeile) -> als PDF speichern oder direkt drucken

**Comment by yannick9906** [comment]
Dafür bräuchten wir doch erstmal ein Design oder?

**Comment by yannick9906** [comment]
^^ Werd ich mir wohl was einfallen lassen und das auf dem nächsten Treffen vorstellen

**Comment by JanikNex** [comment]
@yannick9906 http://www.fpdf.org/ ?

**Comment by JanikNex** [comment]
(Sollte) fertig sein.
